export const COUNTER_REDUCER = "COUNTER_REDUCER"
export const SET_CARD_DECK = "SET_CARD_DECK"
export const SHUFFLE_DECK = "SHUFFLE_DECK"

export const ADD_LAST_CARD = "ADD_LAST_CARD"
export const REMOVE_LAST_CARD = "REMOVE_LAST_CARD"

export const ADD_CARD_TO_REUSALBE = "ADD_CARD_TO_REUSALBE"
export const RESTART_REUSABLE = "RESTART_REUSABLE"